### ISSUE TITLE
Smoking cooking mode as a widget?

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#1]
Give user full control of the flips. Timer starts in 00:00:00 and goes up indefinitely until the user marks a flip (lap).

**Comment by arquicanedo** [comment]
Partially addressed by #19. For a real smoking option we need to figure out how to keep the timer running in the background even when the app is closed. This would be needed as you need to do things throughought the day and use the watch for other purposes. When the timers expire there is hopefully a way to trigger an alarm and bring the barbecue boss app back to the screen for user attention.

**Comment by arquicanedo** [comment]
Quoting @nilsbenson 

> I agree - I think it makes more sense to have a pop-up notification of sorts if we are running as a widget. I haven't looked at the restrictions on them though, so I don't know if we can. Ideally, in that case, it would work similar to the built-in timer in that when it goes off, it pops itself up and lets you do what you need. For grilling this makes less sense, but for smoking/baking/long term cooking it makes more so you don't have to watch it the entire time and can just set-and-forget.

**Comment by arquicanedo** [comment]
The smoking/baking functionality could be a new app. Blending the two functions into one may be cumbersome.

**Comment by nilsbenson** [comment]
https://forums.garmin.com/developer/connect-iq/f/discussion/5439/widget-app

according to this, a widget can't be exposed by a watch app / they have to be two different apps in the store with different manifest IDs. We _can_ support building both out of the same codebase but they won't be able to communicate settings with each other. 

I think the widget/glance view would be super useful for quick checks on smoking, but without some kind of shared data storage it will be difficult. I think we should long term consider a companion app to smooth over some of these rough edges (in particular - for devices without direct bluetooth API access we still want to be able to communicate meat probe info to the app).

I think for now we move forward with implementing smoking in the app with support for "background" timers and get it working. once we have a workable solution we can look at maybe a companion app or apps. 

I also think that since this smoking mode is a different mode/use case/model than the grilling we should maybe look at having the user access the functionality by "nextPage" from the welcome screen. I will see if I can mock up a screenshot of what I'm thinking.

**Comment by arquicanedo** [comment]
Closing as widgets are more constrained than apps.
