### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#29]
Here an email I got today after the user saw the demo video of the current development version.

> Suggestions/hopes ranked by priority:
Each line should contain
Name (S1, S2, etc is fine if you want to save space)

Already covered

> Countdown to next flip maybe as "1:23 - 2" - for 1:23 to the second flip?

Already covered, though in a different format.

> Countdown to total time (and if passed 0, continue but as count-up) - this is important: flip times may be a little off on being on time but you do not want to overcook in total.

The total time is an interesting thought. That would be another decreasing total time to the right of the flip time. But then it would be too much info on the screen. Even if we had the space I feel these are good for some but not all users.

> Status could be coloured with unstarted timers having "start" instead of flip countdown

I think this is covered already. Unstarted are grayed out. Active ones are white, and critical ones are orange/red. 

> Settings
Set total time per steak and number of flips (so the app calculates flip time) - typically you would know the total more than the flip time

I find this interesting. I cook the other way around because by setting up the fire I know what temperature I will have, and how many minutes per flip. But I see how other users may look at the total cooking time, and don't care much about the per-flip time. 

> Allow naming of steaks, maybe just 2 chars so I can better keep track of matching the steak to the timer.

I've never used a text interface on the watch, but I think it would be awful. An alternative would be to give a menu with the most popular steaks: ribeye, nystrip, skirt. 

> Dynamic list so the steak nearest a flip would go at the top of the list. If you make a dynamic list, it does not matter if not all are visible at the same time. Chances are that the ones coming up would be.

We could experiment with it, but the dynamic list sounds very cumbersome to use. Perhaps the first row would be a fixed row with "New Steak", and all below it with the dynamic list. This could work.

> Further comments:
You can delete the "Grill" text - takes too much time
I have a Fenix 6 Sapphire so maybe allow different numbers or different font sizes on different screens?

If we see users want more than 4 steaks we can remove. I agree the "Grill" does not add much value other than giving some context to the screen. The Fenix 6 is now nicely rendered with the new changes.

**Comment by nilsbenson** [comment]
**Total time:**

I think this is useful for things you're cooking that don't require a "correct" flip time. Something that's not seared and doesn't have an internal temp to worry about. Think grilling corn, onion, etc. For corn you just need to make sure it gets rotated and cooked for half an hour or whatever and that it gets rotated regularly but you're not trying to cook it medium rare. I think this is probably useful but we may need to play around a little to figure out how to do it while keeping it fairly simple.

**Status with colors:**

I like the way it is now, but something to keep in mind is color-blind users. Users always ask for colors to denote things, and it's nice to have but there are a lot of people out there who may not be able to distinguish between them. It's always a good idea to have color be additional and the primary method of visually notifying status should be something that doesn't require it. I'm not really sure how to do that here because the font sizes are difficult to work with. Also, I'm not color blind so I don't know how easily someone can distinguish what's there now. Maybe we just sit on any changes until we have a better suggestion. I think it's usable as-is.

**Steak names:**

I actually was thinking about this. For smoking, there are lots of rough guidelines for pork/poultry/beef/etc for cooking by time/temp/weight. I was thinking we could add a smoking calculator which would ask for the meat type and weight and calculate the time, recommended internal temp, and a "flip time" which would be for checking the cooking temp, water, wood, and finally the internal temp of the meat. We won't be able to support it on all devices (because of memory limitations most likely) but it would require a simple meat picker which we could also use for naming the items on the grill timer. Just a thought.

**Dynamic lists:**

This would actually not be difficult - you've already pretty much written it. We just need to encapsulate the meats & their status into a class (maybe a drawable) and onUpdate() we sort them and then draw them. Generally speaking I think this would be a good idea because we could both support potentially larger fixed-length lists of meats and down the road expand it to be dynamic on devices where it's easier to support.

**Larger screens:**

Following up on my previous comment, for larger screens we can allow for a bit more functionality. Basically "growing into the device". I've had to do a lot of this developing web front ends that support desktop to mobile devices and mobile apps that support a variety of phones with different capabilities. The more the watch offers us, the more we can offer the user. What those things are I don't really know other than more refined layouts right now, but users want to see fancier stuff on their fancier devices. This is also going to require working out a "more complicated" build process so that we can keep memory usage low on low-ram devices and only build in the parts of the code that can actually be used. This would involve at least using monkey barrels and probably something along the lines of the #ifdef support discussed here:

https://forums.garmin.com/developer/connect-iq/f/discussion/7733/solution-for-line-by-line-mc-conditional-compilation/1075703#1075703

**Comment by arquicanedo** [comment]
There are a lot of good thoughts here. Throughout today and tomorrow I'll split these into separate Issues so we can track them individually.

**Comment by arquicanedo** [comment]
Created individual Issues. Closing this one.
