### ISSUE TITLE
Meat picker for custom steak names

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#47]
> I actually was thinking about this. For smoking, there are lots of rough guidelines for pork/poultry/beef/etc for cooking by time/temp/weight. I was thinking we could add a smoking calculator which would ask for the meat type and weight and calculate the time, recommended internal temp, and a "flip time" which would be for checking the cooking temp, water, wood, and finally the internal temp of the meat. We won't be able to support it on all devices (because of memory limitations most likely) but it would require a simple meat picker which we could also use for naming the items on the grill timer. Just a thought.

**Comment by arquicanedo** [comment]
I enabled the stringPicker prior to the durationPicker. There is a weird behavior on the pop/push of the views. I'm burned out for today so I don't see it clearly how to implement correctly.

**Comment by arquicanedo** [comment]
My next step is to connect the selected string to the steak names in the list. For efficiency we can probably support up to 2 custom characters. So if I'm grilling corn I customize as CO. If a duplicate entry is found we can add a number to the steak. That is CO, CO1, CO2.

**Comment by arquicanedo** [comment]
I was looking into the options and the basic Menu only accepts text. Menu2 takes icons (https://developer.garmin.com/downloads/connect-iq/monkey-c/doc/Toybox/WatchUi/IconMenuItem.html).

Having an ancient watch sucks.

**Comment by arquicanedo** [comment]
Looking at #37 and the watch-specific build process. It probably makes more sense to simply provide the basic functionality for old watches (e.g., v.1.0.0) and move on with a different app for premium devices CIQ>=3.0.

**Comment by nilsbenson** [comment]
We can write an bitmap picker that works like the other pickers, but instead of a NumberFactory or WordFactory it uses a BitmapFactory (that we write). 

The picker uses the factories to get the items it is supposed to draw as Drawables. It does some other stuff (drawing triangles and stuff) but really it's just drawing something on the screen and telling which value(s) were picked. This can be supported on pretty much all devices.

Take a look at how the StringPicker is written. You could put together an bitmap factory that loads and returns some images (for the meats) and change the drawText calls to drawBitmap instead. 

The newer menus are nice for what we would like to do for the settings menu (because all of the functionality we need is built in to it) but there's nothing preventing us from writing our own controls. What Garmin has provided is decent but I would say there's no doubt in my mind that 95% of the apps in the store have custom UI controls they had to write because what's there is so basic.

The harder part is going to be getting bitmaps/icons that look decent. I downloaded those you sent me and tried making some up from them but they look terrible on device. It's going to take a lot of experimenting to get them looking good on these small displays.

**Comment by arquicanedo** [comment]
@nilsbenson thanks, that sounds promising! I'll take a deeper look at the factories implementations.

**Comment by arquicanedo** [comment]
I pushed the proof of concept. I'm working on the improvement to prompt the flip timer directly if the steak is already running. Only show foodtype selection when the steak is in Controller.INIT status. To change a type of food you first need to stop it. Otherwise is simply a flip change.

**Comment by arquicanedo** [comment]
User feedback.

> June 12, 2020 | Version 1.0.0. I'll never ruin another $20 steak. Great app, easy to install and use. Will make a great Tea timer, and a million other things that require a simple timer. 

The tea timer can be covered by the 046-cofeee-cup icon.

**Comment by arquicanedo** [comment]
Closing this one. Fully addressed in the dynamic-entries branch.
