### ISSUE TITLE
Implement a background service like multi-timer to support long-term timers w/o app running

### ISSUE THREAD

**Issue by nilsbenson** [arquicanedo/barbecueboss#61]
The multi-timer app has a clever way of using a background service with temporal events to keep track of long-running timers while the app is "closed". 

Since app timers are killed when the app closes, we need a way to let something run similarly for extended periods and this seems to be the best approach. This service would be usable by the app, widget, or glance view to see the overall status of a smoking operation.

**Comment by nilsbenson** [comment]
requires CIQ >= 2.4 for background services so this will only work on newer devices.

**Comment by arquicanedo** [comment]
I think this is trivial to emulate with the datastore. Saving the timestamp before closing. On re-opening the app do a diff between the two and recalculate the timer. Obviously, no alarms, but if I'm smoking I would be checking the app. On Saturdays, for example, I put the meat on the smoker and instead of the app I check the time. Then try to remember at what time I started. The older I get the harder it gets to remember whether I started at 7:00 or 8:30 that day. Then do adjustments as I go throughout the day.

Other than the lack of warnings/reminders. Am I missing something?

Another interesting question is whether the datastore is sandboxed in the app. Is there a way to share data among apps? That is, app 1 writes a message for app 2 via de datastore on a shared memory area.

**Comment by nilsbenson** [comment]
According to a bunch of posts on the Garmin forum there's no way on-device to share data between apps. You could do it in a companion app for Connect Mobile though.

You're right - you would lose alerts. It would be easy enough to be able to store/restore state so when the app re-opens it can catch up on the timers. It would also be usable as a widget and all the settings persist between the two.

**Comment by arquicanedo** [comment]
I think this is working with the datastore. Perhaps the only thing would be to look for corner cases like when the timer exceeds the ETA and numbers go negative. I'll look into it.

**Comment by arquicanedo** [comment]
This is handled well by the current implementation. It simply sets to 0. Closing.
