### ISSUE TITLE
[Tenergy/Simulator] Device Scan - takes long to acquire the sensor in the simulator

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#94]
I took a good 10 minutes for the simulator to pick the signal from the Tenergy. Perhaps I'm doing it wrong. But once acquired it keeps it connected.

@nilsbenson Is this the process?

1. Probe Settings -> enable
2. Device Scan (Blank Screen) but I get the lock in the terminal "FOUND Device name: null Appearance: 0 Services:"

Is Step 2 "Device Scan" necessary or does it do it automatically?

I got it to work in the simulator
![Screen Shot 2020-07-14 at 5 36 14 PM](https://user-images.githubusercontent.com/44371316/87478911-8ad50900-c5f8-11ea-9672-4c8d55757c5a.png)

The persistent timer works great.

**Comment by arquicanedo** [comment]
I've been doing some testing. Before getting a lock there are many of these notifications:

FOUND Device name: null Appearance: 0
Services:
========
...

and once in a while
FOUND Device name: null Appearance: 0
Services:
0000FFF0-0000-1000-8000-00805F9B34FB
maybe a tenergy
emitScanResult()
TenergyScanView recv scanResult
service: 0000FFF0-0000-1000-8000-00805F9B34FB TENERGY_SERVICE: 0000FFF0-0000-1000-8000-00805F9B34FB

No temp probes visible. I guess once it gets the sensor data displays it. Will get familiar with the code later.

![Screen Shot 2020-07-14 at 5 50 15 PM](https://user-images.githubusercontent.com/44371316/87480036-8c9fcc00-c5fa-11ea-9f37-db24068aa80a.png)

**Comment by nilsbenson** [comment]
The device scan probably doesn't need to be there. Since we have guess at the device and have no way to uniquely identify it, it starts scanning as soon as you open the SmokeView if you have it enabled. 

The pairing and connecting to the device eventually works, but the Tenergy side of things tends to hang up every once in a while and it takes a second pass to get connected. This can take a while, especially if you turn on the Tenergy and don't immediately connect something to it. I think it goes into low power mode.

To make it work better, turn off the Tenergy and once the app starts scanning turn it on. It will connect immediately and disconnect/reconnect happens faster.

**Comment by nilsbenson** [comment]
Also, yes - I wanted something quick and dirty to let me know when it was or was not connected so I just show/hide the temperatures based on connection state.

**Comment by arquicanedo** [comment]
I really love this. Will try to use it this weekend and smoke something. Can't wait.
